stages:
  - test
<<<<<<< HEAD

realizar_testes:
  stage: test
  image: node:20.7.0-alpine3.17
=======
  - build
  - deploy

realizar_testes:
  stage: test
  image: node:17-alpine3.14
>>>>>>> kubernetes
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
<<<<<<< HEAD
=======
  artifacts:
    when: always
    reports:
        junit: app/junit.xml
  
build_images:
  stage: build
  needs:
    - realizar_testes
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t jeffyuri/dio-lab-k8s:latest
    - docker push jeffyuri/dio-lab-k8s:latest

deploy_dev:
  stage: deploy
  needs:
    - build_images
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@35.198.57.187 "sudo rm * -Rf sudo git clone --branch kubernetes https://gitlab.com/denilsonbonatti/gitlab-cicd-app-base.git && cd gitlab-cicd-app-base && kubectl -f deployment.yml"
>>>>>>> kubernetes
